# Generated by Django 5.0.6 on 2024-08-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='value',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
