# Generated by Django 5.0.6 on 2024-08-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
